services:
  - type: web
    name: marketplace-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: marketplace-db
          property: connectionString
      - key: JWT_SECRET
        sync: false